
question = f"<p><img class=\"lrn-image-center\" height=\"35\" src=\"https://dw6y82u65ww8h.cloudfront.net/organisations/75/42394366-0337-4189-9472-b31dc6d93157.png\" width=\"150\" /></p>\n\n<p>A sequence is generated by repeating the pattern of the five symbols shown above in that order. Which of the following shows the 12th, 13th, 14th, 15th, and 16th symbols in the sequence?</p>\n"

"options":[
{
"label":"<img height=\"18\" src=\"https://dw6y82u65ww8h.cloudfront.net/organisations/75/e613be49-8f6d-4855-b0f6-971eedc13744.png\" width=\"120\" />",
"value":"0"
},
{
"label":"<img height=\"18\" src=\"https://dw6y82u65ww8h.cloudfront.net/organisations/75/093f0d37-d881-4dc8-86ff-3da1e8257c17.png\" width=\"120\" />",
"value":"1"
},
{
"label":"<img height=\"18\" src=\"https://dw6y82u65ww8h.cloudfront.net/organisations/75/20589484-b458-4759-a89b-4a174cec1306.png\" width=\"120\" />",
"value":"2"
},
{
"label":"<img height=\"18\" src=\"https://dw6y82u65ww8h.cloudfront.net/organisations/75/cf0ebeff-f42d-4c5d-834b-405ac5a8d2ca.png\" width=\"120\" />",
"value":"3"
},
{
"label":"<img height=\"18\" src=\"https://dw6y82u65ww8h.cloudfront.net/organisations/75/026d4ada-0f54-425e-b650-3e766bb8ecfd.png\" width=\"120\" />",
"value":"4"
}
]

"distractor_rationale_response_level":[
"You represented the&nbsp;eleventh through fifteenth symbols in the sequence.",
"Since the sequence repeats after every fifth symbol, the pattern shown also represent the eleventh through fifteenth symbols in the sequence. So the pattern starting with the twelfth symbol runs, circle, circle, triangle, triangle, and then continuing with the first symbol in the given pattern, another symbol.",
"You represented the&nbsp;thirteenth through seventeeth symbols in the sequence.",
"You represented the fourteenth through nineteenth symbols in the sequence.",
"You represented the&nbsp;tenth through fourteenth symbols in the sequence."
]
