# Generated by Django 2.2 on 2021-02-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonymansweroption',
            name='synonym',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
        migrations.DeleteModel(
            name='SynonymAnswerOption',
        ),
    ]
