# Generated by Django 2.2 on 2021-02-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_maker', '0002_auto_20210215_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_maker.Definition')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_maker.Word')),
            ],
        ),
        migrations.CreateModel(
            name='SynonymAnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=200)),
                ('answer_type', models.CharField(default='random_word', max_length=100)),
                ('has_been_vetted', models.BooleanField(default=False)),
                ('synonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_maker.Synonym')),
            ],
        ),
    ]
