# Generated by Django 2.2 on 2021-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_maker', '0005_auto_20210219_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1),
        ),
    ]
