# Generated by Django 2.2 on 2021-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_maker', '0006_synonym_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1, null='True'),
        ),
    ]
