# Generated by Django 2.2 on 2021-02-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_maker', '0007_auto_20210219_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymansweroption',
            name='explanation',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
