# Generated by Django 2.2 on 2021-03-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_maker', '0008_synonymansweroption_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], max_length=1)),
                ('relationship', models.CharField(default='synonyms', max_length=50)),
                ('has_been_vetted', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1, null='True')),
                ('word_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogy_word_a_definition', to='question_maker.Definition')),
                ('word_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogy_word_b_definition', to='question_maker.Definition')),
                ('word_C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogy_word_c_definition', to='question_maker.Definition')),
            ],
        ),
        migrations.CreateModel(
            name='AnalogyAnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.CharField(blank=True, max_length=2500, null=True)),
                ('analogy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_maker.Analogy')),
                ('word_C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogy_answer_word_c_definition', to='question_maker.Definition')),
                ('word_D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogy_answer_word_d_definition', to='question_maker.Definition')),
            ],
        ),
    ]
