# Generated by Django 2.2 on 2020-10-09 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('practice_test', 'practice_exercise')], max_length=40)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeExerciseScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('math_1', 'math_1'), ('reading', 'reading'), ('verbal', 'verbal'), ('math_2', 'math_2')], max_length=14, null=True)),
                ('raw_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('sub_section', models.CharField(max_length=200)),
                ('sub_section_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSetQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('diagram', models.CharField(blank=True, max_length=10000, null=True)),
                ('passage', models.CharField(blank=True, max_length=10000, null=True)),
                ('extra_info_text', models.CharField(blank=True, max_length=10000, null=True)),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('option_e', models.CharField(blank=True, max_length=300, null=True)),
                ('correct_answer', models.CharField(max_length=300)),
                ('category_1', models.CharField(max_length=300)),
                ('category_2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_raw', models.IntegerField()),
                ('reading_raw', models.IntegerField()),
                ('verbal_raw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('math_1', 'math_1'), ('reading', 'reading'), ('verbal', 'verbal'), ('math_2', 'math_2')], max_length=14, null=True)),
                ('question_text', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=10)),
                ('question_type', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField()),
                ('diagram_src', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('math_1', 'math_1'), ('reading', 'reading'), ('verbal', 'verbal'), ('math_2', 'math_2')], max_length=14, null=True)),
                ('num_questions', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('test_type', models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=14, null=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('math_1_start_time', models.DateTimeField(blank=True, null=True)),
                ('math_1_finished_time', models.DateTimeField(blank=True, null=True)),
                ('reading_start_time', models.DateTimeField(blank=True, null=True)),
                ('reading_finished_time', models.DateTimeField(blank=True, null=True)),
                ('verbal_start_time', models.DateTimeField(blank=True, null=True)),
                ('verbal_finished_time', models.DateTimeField(blank=True, null=True)),
                ('math_2_start_time', models.DateTimeField(blank=True, null=True)),
                ('math_2_finished_time', models.DateTimeField(blank=True, null=True)),
                ('bullshit', models.DateTimeField(blank=True, null=True)),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.PracticeTestScore')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyCentralIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_type', models.CharField(choices=[('P', 'Prefix'), ('R', 'Root'), ('S', 'Suffix')], max_length=1)),
                ('term', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(blank=True, max_length=20)),
                ('synonyms_list', models.CharField(blank=True, max_length=200)),
                ('definition', models.CharField(blank=True, max_length=500)),
                ('example', models.CharField(blank=True, max_length=1000)),
                ('vocabulary_central_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.VocabularyCentralIdea')),
                ('vocabulary_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.VocabularyRoot')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyTermSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('option_e', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.VocabularyTerm')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('parent', 'parent'), ('instructor', 'instructor'), ('student', 'student')], max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSessionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Section')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession')),
            ],
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(default=-1)),
                ('answered', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_for_test_type', models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Instructor')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('passage_index', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.ReadingPassage'),
        ),
        migrations.AddField(
            model_name='question',
            name='practice_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.PracticeExercise'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Test'),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('practice_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.PracticeExercise')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.PracticeExerciseScore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeExerciseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(default=-1)),
                ('answered', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.PracticeSession')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.UserProfile'),
        ),
        migrations.CreateModel(
            name='AssignmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Assignment')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Instructor'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='practice_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.PracticeExercise'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Test'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('option', models.CharField(max_length=500)),
                ('explanation', models.CharField(blank=True, default='n', max_length=2000, null=True)),
                ('num_students_choice', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Question')),
            ],
        ),
    ]
