# Generated by Django 2.2 on 2020-10-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsession',
            old_name='bullshit',
            new_name='time_finished_math_1',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='math_1_finished_time',
            new_name='time_finished_math_2',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='math_1_start_time',
            new_name='time_finished_reading',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='math_2_finished_time',
            new_name='time_finished_verbal',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='math_2_start_time',
            new_name='time_started_math_1',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='reading_finished_time',
            new_name='time_started_math_2',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='reading_start_time',
            new_name='time_started_reading',
        ),
        migrations.RenameField(
            model_name='testsession',
            old_name='verbal_finished_time',
            new_name='time_started_verbal',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='verbal_start_time',
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_math_1',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_math_2',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_reading',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_verbal',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='practiceexercisescore',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('instructor', 'instructor'), ('parent', 'parent'), ('student', 'student')], max_length=14),
        ),
    ]
