# Generated by Django 2.2 on 2020-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0002_auto_20201027_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='section_math_1',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='section_math_2',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='section_reading',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='section_verbal',
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('C', 'Completed'), ('N', 'Not Started'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('C', 'Completed'), ('N', 'Not Started'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('C', 'Completed'), ('N', 'Not Started'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('C', 'Completed'), ('N', 'Not Started'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='practiceexercisescore',
            name='section',
            field=models.CharField(blank=True, choices=[('reading', 'reading'), ('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('reading', 'reading'), ('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('reading', 'reading'), ('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
    ]
