# Generated by Django 2.2 on 2020-10-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0003_auto_20201027_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='time_finished',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='time_started',
        ),
        migrations.AddField(
            model_name='testsession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practiceexercisescore',
            name='section',
            field=models.CharField(blank=True, choices=[('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading'), ('verbal', 'verbal')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading'), ('verbal', 'verbal')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading'), ('verbal', 'verbal')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('instructor', 'instructor'), ('parent', 'parent')], max_length=14),
        ),
    ]
