# Generated by Django 2.2 on 2020-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0004_auto_20201031_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='test_responses_have_been_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practiceexercisescore',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('reading', 'reading'), ('math_2', 'math_2'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('reading', 'reading'), ('math_2', 'math_2'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('reading', 'reading'), ('math_2', 'math_2'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('parent', 'parent'), ('instructor', 'instructor'), ('student', 'student')], max_length=14),
        ),
    ]
