# Generated by Django 2.2 on 2020-11-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0005_auto_20201111_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTestSectionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14)),
                ('num_correct', models.IntegerField()),
                ('num_incorrect', models.IntegerField()),
                ('num_omitted', models.IntegerField()),
                ('raw_score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='score',
        ),
        migrations.AlterField(
            model_name='practiceexercisescore',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('instructor', 'instructor'), ('student', 'student'), ('parent', 'parent')], max_length=14),
        ),
        migrations.DeleteModel(
            name='PracticeTestScore',
        ),
        migrations.AddField(
            model_name='practicetestsectionscore',
            name='test_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession'),
        ),
    ]
