# Generated by Django 2.2 on 2020-06-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0005_auto_20200615_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('ssat', 'SSAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('math_1', 'MATH_1'), ('reading', 'READING'), ('verbal', 'VERBAL'), ('math_2', 'MATH_2')], max_length=200)),
                ('response', models.IntegerField(default=-1)),
                ('answered', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Question')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession')),
                ('test_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Test')),
            ],
        ),
    ]
