# Generated by Django 2.2 on 2020-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0006_auto_20200616_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresponse',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='testresponse',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='section',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='test_id',
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
