# Generated by Django 2.2 on 2020-06-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0007_auto_20200616_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
    ]
