# Generated by Django 2.2 on 2021-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0012_auto_20210219_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('I', 'In Progress'), ('N', 'Not Started'), ('C', 'Completed')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('parent', 'parent'), ('student', 'student'), ('instructor', 'instructor')], max_length=14),
        ),
    ]
