# Generated by Django 2.2 on 2021-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0013_auto_20210219_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetestsectionscore',
            name='section',
            field=models.CharField(choices=[('math_2', 'math_2'), ('math_1', 'math_1'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=14),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('math_1', 'math_1'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('parent', 'parent'), ('instructor', 'instructor')], max_length=14),
        ),
    ]
