# Generated by Django 2.2 on 2020-06-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0013_auto_20200627_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correctAnswer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading'), ('verbal', 'verbal')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='ssat', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='explanation',
            field=models.CharField(blank=True, default='n', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='num_students_choice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('ssat', 'SSAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
    ]
