# Generated by Django 2.2 on 2021-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0015_auto_20210219_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetestsectionscore',
            name='section',
            field=models.CharField(choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('reading', 'reading'), ('math_1', 'math_1')], max_length=14),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('reading', 'reading'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_1',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_math_2',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_reading',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='section_status_verbal',
            field=models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('I', 'In Progress')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('instructor', 'instructor'), ('student', 'student'), ('parent', 'parent')], max_length=14),
        ),
    ]
