# Generated by Django 2.2 on 2020-07-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0016_auto_20200701_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.ReadingPassage'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='test',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('reading', 'reading'), ('math_2', 'math_2')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('reading', 'reading'), ('math_2', 'math_2')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('ssat', 'SSAT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('ssat', 'SSAT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
    ]
