# Generated by Django 2.2 on 2021-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0016_auto_20210219_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetestsectionscore',
            name='section',
            field=models.CharField(choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('ssat', 'SSAT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('ssat', 'SSAT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('instructor', 'instructor'), ('parent', 'parent'), ('student', 'student')], max_length=14),
        ),
    ]
