# Generated by Django 2.2 on 2020-07-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0018_auto_20200701_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('reading', 'reading'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('verbal', 'verbal')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('reading', 'reading'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('verbal', 'verbal')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='TestSessionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Section')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession')),
            ],
        ),
    ]
