# Generated by Django 2.2 on 2020-07-04 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ace_it_test_prep', '0020_auto_20200704_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('reading', 'reading'), ('math_1', 'math_1'), ('verbal', 'verbal')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('reading', 'reading'), ('math_1', 'math_1'), ('verbal', 'verbal')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_for_test_type', models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
