# Generated by Django 2.2 on 2020-07-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0022_auto_20200704_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('reading', 'reading'), ('verbal', 'verbal'), ('math_1', 'math_1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('reading', 'reading'), ('verbal', 'verbal'), ('math_1', 'math_1')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_profile',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('s', 'student'), ('i', 'instructor'), ('p', 'parent')], default='1', max_length=4),
            preserve_default=False,
        ),
    ]
