# Generated by Django 2.2 on 2020-07-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0023_auto_20200704_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('math_1', 'math_1'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('math_1', 'math_1'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('p', 'parent'), ('s', 'student'), ('i', 'instructor')], max_length=4),
        ),
    ]
