# Generated by Django 2.2 on 2020-07-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0027_auto_20200707_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='test_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('verbal', 'verbal'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('verbal', 'verbal'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('p', 'parent'), ('i', 'instructor'), ('s', 'student')], max_length=4),
        ),
    ]
