# Generated by Django 2.2 on 2020-07-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0028_auto_20200707_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='test_session',
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('reading', 'reading'), ('math_1', 'math_1'), ('verbal', 'verbal')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('reading', 'reading'), ('math_1', 'math_1'), ('verbal', 'verbal')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('i', 'instructor'), ('p', 'parent'), ('s', 'student')], max_length=4),
        ),
        migrations.CreateModel(
            name='AssignmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.Assignment')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ace_it_test_prep.TestSession')),
            ],
        ),
    ]
