# Generated by Django 2.2 on 2020-09-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0042_auto_20200909_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocuabularyRoot',
            new_name='VocabularyRoot',
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('reading', 'reading'), ('math_1', 'math_1'), ('math_2', 'math_2')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('reading', 'reading'), ('math_1', 'math_1'), ('math_2', 'math_2')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('act', 'ACT'), ('sat', 'SAT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('parent', 'parent'), ('instructor', 'instructor')], max_length=14),
        ),
    ]
