# Generated by Django 2.2 on 2020-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0045_auto_20200909_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyterm',
            name='definition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('instructor', 'instructor'), ('parent', 'parent')], max_length=14),
        ),
        migrations.AlterField(
            model_name='vocabularyroot',
            name='root_type',
            field=models.CharField(choices=[('P', 'Prefix'), ('R', 'Root'), ('S', 'Suffix')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vocabularyterm',
            name='example',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vocabularyterm',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vocabularyterm',
            name='synonyms_list',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
