# Generated by Django 2.2 on 2020-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0052_auto_20200910_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularytermsynonym',
            old_name='correct_anwser',
            new_name='correct_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('math_1', 'math_1'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('math_2', 'math_2'), ('math_1', 'math_1'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('sat', 'SAT'), ('act', 'ACT')], max_length=4, null=True),
        ),
    ]
