# Generated by Django 2.2 on 2020-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0053_auto_20200911_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('sub_section', models.CharField(max_length=200)),
                ('sub_section_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSetQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('diagram', models.CharField(blank=True, max_length=10000, null=True)),
                ('passage', models.CharField(blank=True, max_length=10000, null=True)),
                ('extra_info_text', models.CharField(blank=True, max_length=10000, null=True)),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('option_e', models.CharField(blank=True, max_length=300, null=True)),
                ('correct_answer', models.CharField(max_length=300)),
                ('category_1', models.CharField(max_length=300)),
                ('category_2', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_2', 'math_2'), ('math_1', 'math_1'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('ssat', 'SSAT'), ('act', 'ACT'), ('sat', 'SAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('parent', 'parent'), ('instructor', 'instructor')], max_length=14),
        ),
    ]
