# Generated by Django 2.2 on 2020-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_it_test_prep', '0054_auto_20200912_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCentralIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, choices=[('verbal', 'verbal'), ('math_1', 'math_1'), ('math_2', 'math_2'), ('reading', 'reading')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prep_for_test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(blank=True, choices=[('sat', 'SAT'), ('act', 'ACT'), ('ssat', 'SSAT')], max_length=4, null=True),
        ),
    ]
